- name: Reverse Proxy Setup
  block:
    - name: Copying configuration
      template:
        src: 'project.j2'
        dest: '/etc/nginx/conf.d/{{ item.ServerName }}.{{ item.fulldomainname }}.conf'
        owner: root
        group: root
        mode: "644"
      loop: "{{ server.info }}"

    # - name: Generate Basic Authen
    #   htpasswd:
    #     path: /etc/nginx/authen/.htpasswd-{{ item.ServerName }}
    #     name: "{{ item.ServerName }}.{{ item.fulldomainname }}"
    #     password: "{{ item.password }}"
    #     owner: root
    #     group: root
    #     mode: '640'
    #   loop: "{{ server.info }}"
    
    - name: Generate Basic Authen
      command:  "htpasswd -c -b .htpasswd-{{ item.ServerName }} {{ item.ServerName }}.{{ item.fulldomainname }} {{ item.password }}"
      args:
        chdir: /etc/nginx/authen/
      loop: "{{ server.info }}"
      notify: Reload Reverse-Proxy
      


