---
# tasks file for roles/local-confdig

- name: Changing Hostname
  hostname: 
    name: "{{ item.project }}"
  loop: "{{ server_info }}"

- name: Changing /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^(.*)127(.*)$"
    line: "127.0.0.1 {{ item.project }}"
    state: "present"
  loop: "{{ server_info }}"

# CentOS
- name: CentOS Local Config
  block:
    - name: Changing IP Address
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: "{{ ansible_host }}" 
        replace: "{{ item.ipv4 }}"
      loop: "{{ server_info }}"

    - name: Deleting extra ssh config line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        state: "absent"

    - name: Changing ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        line: "PasswordAuthentication no"
        state: "present"  
      notify: Restart SSH Service
  when: ansible_facts['distribution'] == "CentOS"

# Debian
- name: Ubuntu/Debian Local Config
  block:
    # - name: Deleting extra ssh config line
    #   lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: "PasswordAuthentication yes"
    #     state: "absent"

    - name: Changing ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        state: "present"
      notify: Restart SSH Service

    - name: Changing IP Address
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        backrefs: yes
        regexp: '^(\s*)[#]?- {{ ansible_host }}(: )*' 
        line: '\1- {{ item.ipv4 }}/24'
        state: "present"
      loop: "{{ server_info }}"
      notify: Restart Netplan
  when: ansible_facts['distribution'] == "Ubuntu"